parser: babel-eslint
parserOptions:
  sourceType: module
  ecmaVersion: 2019
env:
  es6: true
  browser: true
overrides:
  - files: '**/*.svelte'
    processor: 'svelte3/svelte3'
plugins:
  - svelte3
